#!/usr/bin/env bash
# OpenATC — Server setup script
# Detects GPU, installs nvidia-container-toolkit if needed,
# writes a run.sh that starts the correct Docker Compose configuration.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

echo "=== OpenATC Server Setup ==="
echo ""

# --- Check prerequisites ---
echo "[1/4] Checking prerequisites..."

# Check Docker
if ! command -v docker &> /dev/null; then
    echo "ERROR: Docker is not installed."
    echo "Install Docker first: https://docs.docker.com/engine/install/ubuntu/"
    exit 1
fi
echo "      Docker: $(docker --version)"

# Check Docker Compose (v2)
if ! docker compose version &> /dev/null; then
    echo "ERROR: Docker Compose (v2) is not available."
    echo "Install Docker Compose: https://docs.docker.com/compose/install/"
    exit 1
fi
echo "      Docker Compose: $(docker compose version)"

# Check Python for entrypoint scripts (for voice download, etc.)
if ! command -v python3 &> /dev/null; then
    echo "ERROR: Python 3 is required for the entrypoint scripts."
    exit 1
fi

# --- GPU detection ---
echo "[2/4] Detecting GPU..."
GPU_FOUND=false
NVIDIA_TOOLKIT_INSTALLED=false

if command -v nvidia-smi &> /dev/null; then
    echo "      Nvidia GPU detected:"
    nvidia-smi --query-gpu=name,memory.total --format=csv,noheader 2>/dev/null | \
        sed 's/^/      - /'
    GPU_FOUND=true

    # Check nvidia-container-toolkit
    if docker info 2>/dev/null | grep -q "nvidia"; then
        NVIDIA_TOOLKIT_INSTALLED=true
        echo "      nvidia-container-toolkit: installed"
    fi
else
    echo "      No Nvidia GPU detected (running in CPU-only mode)"
fi

# --- Install nvidia-container-toolkit if needed ---
echo "[3/4] Configuring GPU support..."

RUN_CMD="docker compose -f docker-compose.yml"

if [ "$GPU_FOUND" = true ] && [ "$NVIDIA_TOOLKIT_INSTALLED" = false ]; then
    echo ""
    echo "      nvidia-container-toolkit is required for GPU acceleration in Docker."
    echo "      This allows Ollama (LLM) and Whisper (STT) to use your GPU."
    echo ""

    read -rp "      Install nvidia-container-toolkit now? (requires sudo) [Y/n]: " choice
    choice=${choice:-Y}

    if [[ "$choice" =~ ^[Yy]$ ]]; then
        echo "      Installing nvidia-container-toolkit..."
        
        # Detect distribution
        if [ -f /etc/os-release ]; then
            . /etc/os-release
            if [ "$ID" = "ubuntu" ] || [ "$ID" = "debian" ]; then
                curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | \
                    sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
                curl -sL "https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list" | \
                    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
                    sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
                sudo apt-get update -qq
                sudo apt-get install -y -qq nvidia-container-toolkit
                sudo nvidia-ctk runtime configure --runtime=docker
                sudo systemctl restart docker
                echo "      nvidia-container-toolkit installed. Docker restarted."
                NVIDIA_TOOLKIT_INSTALLED=true
            else
                echo "      Unsupported distribution ($ID). Please install manually:"
                echo "      https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html"
            fi
        fi
    else
        echo "      Skipping. GPU will not be available in containers."
    fi
fi

# Determine final run command
if [ "$GPU_FOUND" = true ] && [ "$NVIDIA_TOOLKIT_INSTALLED" = true ]; then
    RUN_CMD="docker compose -f docker-compose.yml -f docker-compose.gpu.yml"
    echo "      GPU mode: enabled"
else
    echo "      GPU mode: disabled (CPU-only)"
fi

# --- Write run.sh ---
cat > run.sh << EOF
#!/usr/bin/env bash
# Generated by setup.sh — $(date)
set -euo pipefail
cd "$(dirname "$0")"
echo "Starting OpenATC Server..."
$RUN_CMD up -d
echo ""
echo "OpenATC is running!"
echo "  - WebSocket: ws://<server-ip>:${SERVER_PORT:-8765}/ws"
echo "  - API:       http://<server-ip>:${SERVER_PORT:-8765}/health"
echo ""
echo "Stop with:  docker compose down"
echo "Logs:       docker compose logs -f"
EOF
chmod +x run.sh

echo ""
echo "[4/4] Setup complete!"
echo ""
echo "To start the server, run:"
echo "  bash run.sh"
echo ""
echo "To stop the server:"
echo "  docker compose down"
