<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <AssemblyName>OpenATC.Client</AssemblyName>
    <RootNamespace>OpenATC.Client</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.FlightSimulator.SimConnect" Version="10.0.61251.0" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="Concentus" Version="2.2.2" />
    <PackageReference Include="Vortice.DirectInput" Version="3.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.12" />
  </ItemGroup>

</Project>
